set(_CATKIN_CURRENT_PACKAGE "ros_lidar")
set(ros_lidar_VERSION "0.0.0")
set(ros_lidar_MAINTAINER "vision <vision@todo.todo>")
set(ros_lidar_PACKAGE_FORMAT "2")
set(ros_lidar_BUILD_DEPENDS )
set(ros_lidar_BUILD_EXPORT_DEPENDS )
set(ros_lidar_BUILDTOOL_DEPENDS "catkin")
set(ros_lidar_BUILDTOOL_EXPORT_DEPENDS )
set(ros_lidar_EXEC_DEPENDS )
set(ros_lidar_RUN_DEPENDS )
set(ros_lidar_TEST_DEPENDS )
set(ros_lidar_DOC_DEPENDS )
set(ros_lidar_URL_WEBSITE "")
set(ros_lidar_URL_BUGTRACKER "")
set(ros_lidar_URL_REPOSITORY "")
set(ros_lidar_DEPRECATED "")