set(_CATKIN_CURRENT_PACKAGE "turtlebot3_nav_cartographer")
set(turtlebot3_nav_cartographer_VERSION "0.0.0")
set(turtlebot3_nav_cartographer_MAINTAINER "Zacharias <zactyl-5@student.ltu.se>")
set(turtlebot3_nav_cartographer_PACKAGE_FORMAT "2")
set(turtlebot3_nav_cartographer_BUILD_DEPENDS "roslaunch" "roscpp" "rospy" "std_msgs" "turtlebot3" "amcl" "cartographer_ros" "move_base" "robot_state_publisher" "rviz")
set(turtlebot3_nav_cartographer_BUILD_EXPORT_DEPENDS "amcl" "cartographer_ros" "move_base" "robot_state_publisher" "rviz")
set(turtlebot3_nav_cartographer_BUILDTOOL_DEPENDS "catkin" "catkin_make_isolated")
set(turtlebot3_nav_cartographer_BUILDTOOL_EXPORT_DEPENDS )
set(turtlebot3_nav_cartographer_EXEC_DEPENDS "std_msgs" "amcl" "cartographer_ros" "move_base" "robot_state_publisher" "rviz" "roscpp" "rospy")
set(turtlebot3_nav_cartographer_RUN_DEPENDS "std_msgs" "amcl" "cartographer_ros" "move_base" "robot_state_publisher" "rviz" "roscpp" "rospy")
set(turtlebot3_nav_cartographer_TEST_DEPENDS "roslaunch" "rosunit")
set(turtlebot3_nav_cartographer_DOC_DEPENDS )
set(turtlebot3_nav_cartographer_URL_WEBSITE "")
set(turtlebot3_nav_cartographer_URL_BUGTRACKER "")
set(turtlebot3_nav_cartographer_URL_REPOSITORY "")
set(turtlebot3_nav_cartographer_DEPRECATED "")